### PR TITLE
Add const string literals

### PR DESCRIPTION
**Pull request by Rixxc**
This pull requests adds the basic ability to define u8 arrays by ascii strings, as requested by #510.

### CODE REVIEW

**Comment by Rixxc** [comment]
I'm not 100% confident in my changes to compiler/src/latex_printer.ml.

The resulting assembly code from the test file is:
```
	.att_syntax
	.text
	.p2align	5
	.globl	_main
	.globl	main
_main:
main:
	movb	$84, %al
	movb	glob_data + 0(%rip), %cl
	xorb	%cl, %al
	ret 
	.data
	.p2align	5
_glob_data:
glob_data:
      .byte 84
      .byte 101
      .byte 115
      .byte 116
      .byte 115
      .byte 116
      .byte 114
      .byte 105
      .byte 110
      .byte 103
```

**Comment by vbgl** [comment]
Thanks for your contribution. I took the liberty to add a few words in the CHANGELOG, add a test for ARM, and clean a bit the LATEX printer.

**Comment by vbgl** [comment]
Also, you may want to add your name in the AUTHORS file.

**Comment by Rixxc** [comment]
I have added myself to AUTHORS. Thank you.

**Review by vbgl — APPROVED** [review]

**Pull request merged**
