### PR TITLE
eclib: addc & zlog2

### PR DESCRIPTION
**Pull request by vbgl**
Let’s keep the various branches in sync.

### CODE REVIEW

**Comment by eponier** [comment]
What branch are these commits coming from?

**Comment by vbgl** [comment]
They are new!

**Comment by eponier** [comment]
So I fail to understand: what is kept in sync then?

**Comment by vbgl** [comment]
https://github.com/jasmin-lang/jasmin/blob/constant-time-op/eclib/JModel.ec#L569-L588

**Comment by eponier** [comment]
Oh ok, I wrote "commit", but I meant more generally "where does this code come from?".

**Review by eponier — APPROVED** [review]
Nice.

**Pull request merged**
