### PR TITLE
varalloc: system calls do modify the stack pointer

### LINKED ISSUE #870: Cannot use #randombytes if there is no stack
The following program is rejected by the Jasmin compiler:

~~~
export
fn rand(reg ptr u8[32] io) -> reg ptr u8[32] {
  io = #randombytes(io);
  return io;
}
~~~

> "tmp/rand.jazz", line 1 (0) to line 5 (1):
compilation error in function rand:
linearization: bad save-stack

Reported by Aaron (@Rixxc).

### PR DESCRIPTION
**Pull request by vbgl**
Fixes #870.

### CODE REVIEW

**Review by eponier — COMMENTED** [review]
I understand why you add a new condition, but not why you remove `ra_on_stack`. Can you explain why it is not there anymore?

**Comment by vbgl** [comment]
You’re right. This change is unrelated, sorry. I’ve removed the condition because it is redundant with the previous one: `ra_on_stack` implies the stack size being non-zero.

**Review by eponier — APPROVED** [review]
Indeed, thanks!

**Comment by eponier** [comment]
(I have no problem shipping the cleaning in this PR, it was just not clear to me that it was correct or on purpose)

**Pull request merged**
