### PR TITLE
x86: fix semantics of VPSHUFB and VPCMPGT

### PR DESCRIPTION
**Pull request by vbgl**
(based on top of #446 to prevent future merge conflicts)

### CODE REVIEW

**Comment by vbgl** [comment]
Yes. VPSHUFB looks OK; VPCMPGT was wrong too.

**Comment by bgregoir** [comment]
I was stupid, it is the first file ?

**Review by bgregoir — APPROVED** [review]

**Comment by bgregoir** [comment]
Why it is still a draft ?

**Comment by vbgl** [comment]
It is ready now.

**Pull request merged**
