### PR TITLE
Prepare for release 2022.09.0

### PR DESCRIPTION
**Pull request by vbgl**

### CODE REVIEW

**Comment by eponier** [comment]
Why did you remove the constraint on coqword?

**Comment by vbgl** [comment]
Because I don’t know how opam works and it failed to satisfy that constraint.

**Comment by vbgl** [comment]
Failure log: https://gitlab.com/jasmin-lang/jasmin/-/jobs/3095825815

**Comment by eponier** [comment]
Oh probably there is no opam package for that release yet.

**Comment by vbgl** [comment]
I let you merge if you agree.

**Comment by eponier** [comment]
Let's try to put the constraint back now that https://github.com/jasmin-lang/coqword/pull/14 has been merged.

**Comment by vbgl** [comment]
CI is happy with the extra constraint in the `opam` file.

**Review by eponier — APPROVED** [review]

**Comment by eponier** [comment]
I let you merge when you want, so that you can branch just afterwards.

**Comment by eponier** [comment]
I guess #254 and https://github.com/jasmin-lang/jasmin/pull/256 should be merged first?

**Comment by vbgl** [comment]
Shall we rename the putative next version as 2022.10.0?

**Comment by eponier** [comment]
If we release soon, I don't think that's needed.

**Pull request merged**
