### PR TITLE
License should not be empty

### PR DESCRIPTION
**Pull request by ildyria**

### CODE REVIEW

**Comment by strub** [comment]
@vbgl Is GPL2 the license we want?

**Comment by vbgl** [comment]
Indeed, GPL is wrong. Now that we got rid of CompCert modules, we can elect the license we want.

Why don’t we also get rid of this `opam` file? Does the Jasmin team supports defective by design software development?

**Comment by strub** [comment]
I use opam and find nix utterly slow on my computer. So let’s keep this
file that doesn’t interfere we other systems.

Regarding the licence, I trust your choice. Please, propose the one your
prefer.

Le ven. 5 oct. 2018 à 19:09, Vincent Laporte <notifications@github.com> a
écrit :

**Comment by vbgl** [comment]
What about CeCILL-B?

**Comment by strub** [comment]
Fine by me

**Pull request merged**
