### PR TITLE
x86: remove support for explicit if-then-else in flag combinations

### PR DESCRIPTION
**Pull request by vbgl**
A comment says this should be removed…

Does this need an entry in the CHANGELOG?

### CODE REVIEW

**Comment by eponier** [comment]
Does it change anything for users?

cc @bgregoir who wrote that comment (commit 33d6b62dc11a5c37ed8feb92cfd87a28036e3438)

**Comment by vbgl** [comment]
This can break legacy code (if the programmer explicitly wrote something like: `x = y if (sf ? !of : of)`, which can easily be written as `x = y if sf != of`, up to typo).

My belief is that no such legacy code exist.

**Comment by eponier** [comment]
Ok, but it is preferable to have something written down in the changelog then, I think. The explanation can be short.

**Comment by vbgl** [comment]
I’ve just added a line into the changelog.

**Review by eponier — APPROVED** [review]
Nice changelog message!

**Pull request merged**
