### PR TITLE
Rework of the error system in Coq and OCaml

### PR DESCRIPTION
**Pull request by eponier**
This should give nicer and more uniform errors and warnings.

Fixes https://github.com/jasmin-lang/jasmin/issues/13 https://github.com/jasmin-lang/jasmin/issues/32 https://github.com/jasmin-lang/jasmin/issues/55

### CODE REVIEW

**Comment by eponier** [comment]
@vbgl The commit that adds colors is the last one. Can you take a look at it to check that it does not prevent you from doing you js-things?

**Comment by eponier** [comment]
Apparently, it does not compile. I must have failed my rebase.

**Comment by eponier** [comment]
Ok, it seems to work actually. I'm merging.

**Comment by eponier** [comment]
Ok, I rebased on the latest glob_array3. @vbgl do you have some comments or do you want to have the time to take a look at this PR? Otherwise, I'll merge.

**Review by vbgl — APPROVED** [review]
Nice work. Thanks!

**Pull request merged**
