### PR TITLE
ARM: mark the export functions as .global

### PR DESCRIPTION
**Pull request by vbgl**
CI: https://gitlab.com/jasmin-lang/jasmin/-/pipelines/785407903

### CODE REVIEW

**Review by sarranz — APPROVED** [review]
Note that this is a bit different from what we do for x86, where we print all the `.global` directives at the top, but obviously this is perfectly OK as well.

**Comment by vbgl** [comment]
Ah, well spotted. I don’t know whether this is important. My main concern is that the linker can find the symbol…

**Comment by sarranz** [comment]
My understanding is that there is no difference between these to options, and it's good for now.
I started modularizing the printer to share more code with x86, and this is one of the parts that I abstract from both printers (printing all `.global`s at the top). I don't know if anybody cares that we print directives this way until I'm done with that other PR. It's taking me a while because I can't figure out how to load global variables properly in ARM, so I think this is good.

**Comment by vbgl** [comment]
Great. Let’s merge as is then.

**Pull request merged**
