### PR TITLE
Remove x86_decl_core and arm_decl_core

### PR DESCRIPTION
**Pull request by eponier**
When explaining the files to other people, we noticed that some functions were duplicated.

### CODE REVIEW

**Review by vbgl — DISMISSED** [review]

**Comment by eponier** [comment]
Actually Benjamin wonders whether the patch should be the reverse one, removing the functions from the files `*_decl_core.v`. It's just a matter of where to put the definitions and how to name them (`string_of_reg` or `reg_to_string`).

**Comment by bgregoir** [comment]
It was more a remark for uniformity. I do not really care.

**Comment by eponier** [comment]
I have a better patch.

**Comment by eponier** [comment]
Actually, x86_decl_core and arm_decl_core.v are now useless. The right patch is to remove them.

**Review by bgregoir — APPROVED** [review]

**Comment by eponier** [comment]
Oups, I did some mistake.

**Review by vbgl — APPROVED** [review]

**Pull request merged**
