### PR TITLE
linear: simplify StoreLabel and make it portable across architectures

### PR DESCRIPTION
**Pull request by vbgl**
As of today, the semantics of the linear language is architecture-dependent. I think it is a mistake.

### CODE REVIEW

**Comment by eponier** [comment]
This change to linear_sem was in my opinion one of the ugliest changes that we did to make Jasmin less architecture-specific, so I'm glad to see your PR. But let me first do the release.

**Review by eponier — APPROVED** [review]
Change very welcome.

Do you recall why it was like this before? Relying on LEA/MOV instead of directly write in the state?

**Comment by vbgl** [comment]
IIRC, I found that it was elegant ;-)

**Comment by eponier** [comment]
Fair enough!

**Pull request merged**
