### PR TITLE
CI: add a coq-master job

### PR DESCRIPTION
**Pull request by vbgl**
This job compiles the Coq sources of the Jasmin compiler with the current master branch of Coq.

### CODE REVIEW

**Review by eponier — APPROVED** [review]
The patch is simple, but what is the motivation?

**Comment by vbgl** [comment]
Comply with the rules of Coq CI: https://raw.githubusercontent.com/coq/coq/533a28779a0c8e861304a3e3f0e5d27b7fda735f/dev/ci/README-users.md

> - You do not push, to the branches that we test, commits that haven't been
  first tested to compile with the corresponding branch(es) of Coq.

**Comment by eponier** [comment]
Fine, then.

**Comment by vbgl** [comment]
Maybe that was a bad idea… Switching to mathcomp-2 will bring in new dependencies (elpi, hb) that I have no clue how to use with the development branch of coq.

**Comment by eponier** [comment]
Do you mean that these dependencies have a lot of differences between Coq 8.19 and Coq master?

**Comment by vbgl** [comment]
I mean that I don’t know how to build `elpi` with the current development version of Coq.

**Comment by vbgl** [comment]
Ok, in fact I do, they have a `coq-master` branch…

**Pull request merged**
