### PR TITLE
Extract to native strings

### PR DESCRIPTION
**Pull request by eponier**
It gives more readable extracted code and maybe better perf.

Maybe some more cleaning is possible, e.g. is `module Name` (in coreIdent) useful?

Based on https://github.com/jasmin-lang/jasmin/pull/804

### CODE REVIEW

**Review by vbgl — CHANGES_REQUESTED** [review]
Please first remove the use of `NilEmpty.string_of_uint` in `makeReferenceArguments`.

**Comment by vbgl** [comment]
That’s up to you. But that other PR shall be merged before this one.

**Comment by eponier** [comment]
Working on it.

**Comment by eponier** [comment]
> Working on it.

Done.

**Comment by eponier** [comment]
#804 was merged, I rebased this on top of latest main.

**Review by vbgl — APPROVED** [review]

**Pull request merged**
