### PR TITLE
Cleaning

### PR DESCRIPTION
**Pull request by eponier**
Two independent patches.

### CODE REVIEW

**Comment by vbgl** [comment]
Thanks. I’ve just added my unrelated stuff ;-)

**Comment by vbgl** [comment]
CI suggests future work (not to be addressed here):

> Error: Cannot extract nontrivial sort polymorphism

**Review by vbgl — APPROVED** [review]
Before merging, it would be nice if someone could give a look to the third commit.

**Comment by eponier** [comment]
> Before merging, it would be nice if someone could give a look to the third commit.
Trivial removal of unused lemmas, so ok to me. I was sure that they were used, but apparently not anymore.

**Pull request merged**
