### PR TITLE
ARM lowering: assignment of large (truncated) integers

### LINKED ISSUE #375: Bitwise negation of an immediate does not work
This example gives an internal error:
```
export
fn main() -> reg u64 {
    reg u64 x;
    x = !1;
    return x;
}
```
both in x86 and arm-m4, but at different passes.

### PR DESCRIPTION
**Pull request by vbgl**
Fixes #375

### CODE REVIEW

**Review by bgregoir — COMMENTED** [review]
Hi Vincent, can you explain what was the problem?
The path suggest that 1 was viewed has a (word_of_int U64 1). I wonder if the patch is the good one. I do not understand why we obtain a U64 in this example. Maybe the good patch should be in pretyping. 
Also 375, say that we also have a problem in x86. It is still true ?

**Comment by vbgl** [comment]
Pretyping infers the missing size annotation for the bitwise negation: `256u`; then inserts a word-of-int at that siz.

**Comment by vbgl** [comment]
Regarding x86-64, I don’t know what the issue might have been. The given program compiles fine for x86 in all version I’ve tested.

**Review by bgregoir — APPROVED** [review]
Thank for the explanation.

**Pull request merged**
