### PR TITLE
Adapt w.r.t. jasmin-lang/coqword#12.

### PR DESCRIPTION
**Pull request by ppedrot**
Hopefully this should fix the Coq CI.

### CODE REVIEW

**Comment by vbgl** [comment]
Is there any way to write code that would be compatible with both versions of coqword?

**Comment by ppedrot** [comment]
Not that I know of.

**Comment by strub** [comment]
We could revert in coqword and de ide to change the namespace only for the next release.

**Review by vbgl — APPROVED** [review]
I guess that a new release of `coqword` would be appropriate indeed.

**Comment by ppedrot** [comment]
Whatever you do, please do it swiftly so that we can get a green CI in Coq asap.

**Comment by ppedrot** [comment]
Thanks!

**Pull request merged**
