### PR TITLE
Add x86 instructions CLFLUSH, LFENCE, MFENCE, SFENCE

### PR DESCRIPTION
**Pull request by vbgl**
Draft until there is agreement on the concrete syntax.

### CODE REVIEW

**Comment by vbgl** [comment]
CI: https://gitlab.com/jasmin-lang/jasmin/-/pipelines/752997195

**Review by bgregoir — CHANGES_REQUESTED** [review]
You should also add some dummy operators in eclib JModel. 
Else the extraction will fail.
Expect that I approve it

**Comment by vbgl** [comment]
Producing valid EasyCrypt code is tough: `() <- LFENCE;` is not accepted, the l-value must be named. But the mechanism for generating fresh variables in `toEC.ml` is not ready to deal with variables of type `unit`.

A possible work around would be to skip those instructions in extraction (maybe produce some leakage for `CLFLUSH` when extracting for CT) as they have no input, no output, and no effect on the semantics. What do you think?

**Comment by vbgl** [comment]
Extraction to EC no longer fails.
CI: https://gitlab.com/jasmin-lang/jasmin/-/pipelines/753977355

**Review by bgregoir — APPROVED** [review]
I am not fan of the current solution. But it is clearly correct.

**Pull request merged**
