### PR TITLE
Register allocation: register banks depend on arch

### LINKED ISSUE #201: ARM: internal error with argument of wrong size
Calling the ARM-version of the compiler on the program
```
export
fn main (reg u64 state)  {
}
```
returns
```
"", line 1 (0) to line 3 (1):
internal compilation error in function main:
  Variable allocation: state (defined at "test_gimli.jazz", line 2 (18-23)) and r0 (defined at "", line -1 (-1)) : type mismatch
Please report at https://github.com/jasmin-lang/jasmin/issues
```

The problem comes from the argument being `u64` and not `u32`. Maybe the program should be rejected, but it should be in a proper way. Moreover, locations of the function and of `r0` are wrong.

### PR DESCRIPTION
**Pull request by vbgl**
The classification of registers between general-purpose “word”-sized registers and “vector” registers depends on the architecture.

Fixes #201

### CODE REVIEW

**Comment by vbgl** [comment]
Where am I supposed to put the test case that is expected to fail?

(ping @sarranz)

**Comment by sarranz** [comment]
> Where am I supposed to put the test case that is expected to fail?
> 
> (ping @sarranz)

If we want to merge this now, maybe we can create `compiler/examples/arm-m4/fail`. But I can push and PR the restructured test directories today, if that's preferable.

**Comment by vbgl** [comment]
There is no hurry, but indeed it would be nice to have a more general testing infrastructure for ARM.

**Comment by sarranz** [comment]
> There is no hurry, but indeed it would be nice to have a more general testing infrastructure for ARM.

I have only the five files we discussed on Zulip to sort out and it's done.

**Review by bgregoir — APPROVED** [review]

**Comment by vbgl** [comment]
I may also just remove the test case: I’m not sure it has a lot of value…

**Pull request merged**
