### PR TITLE
CI: test EasyCrypt extraction

### LINKED ISSUE #104: EasyCrypt in Jasmin's CI
- what version of EasyCrypt shoud we use?
- what do we want to test?

### LINKED ISSUE #136: Test the extraction to EasyCrypt
We were reported a few bugs (https://github.com/jasmin-lang/jasmin/issues/128, https://github.com/jasmin-lang/jasmin/issues/130, https://github.com/jasmin-lang/jasmin/issues/135) of the extraction to EasyCrypt recently, it would be good to have tests for it, because it seems we have none for the moment. The tests would be complementary to having libjade in the CI (which would be good too).

### PR DESCRIPTION
**Pull request by vbgl**
Fixes #104 
Fixes #136

### CODE REVIEW

**Comment by eponier** [comment]
What is the purpose of the 1st commit?

**Comment by vbgl** [comment]
Test more things! (without listing them all explicitly)

**Comment by eponier** [comment]
What is the meaning of `!`? And why turn some functions inline?

**Comment by vbgl** [comment]
`!` is for recursion into sub-directory.

Functions that are just proof artifacts, intermediate programs to build an equivalence proof with hops, are not meant to be compiled: marking them `inline` prevents the compiler to attempt at compiling them down to assembly; yet they are included in the test-suite for type-checking and extraction to EC.

**Pull request merged**
