### PR TITLE
Linear: simplify the types of expressions and of L-values

### PR DESCRIPTION
**Pull request by vbgl**
This is meant as a simplification. But maybe it is not. Any thoughts?

### CODE REVIEW

**Comment by bgregoir** [comment]
This change seems to be relatively large. Are we sure that there is a benefice ?

**Review by bgregoir — CHANGES_REQUESTED** [review]
Improve error messages in linearisation, they should not be internal...

**Review by bgregoir — COMMENTED** [review]
Load and Store should have type wsize & lea

**Review by bgregoir — COMMENTED** [review]
Load and Store should have type wsize & lea
Give access to printLinear.pp_fexpr in Coq, this should allows to remove pexpr_of_fexpr

**Review by bgregoir — COMMENTED** [review]
Load and Store should have type wsize & lea
Give access to printLinear.pp_fexpr in Coq, this should allows to remove pexpr_of_fexpr
rename fexpr -> lexpr
              lexpr -> lout | ldest 
              rexpr -> lin | lsrc

**Comment by vbgl** [comment]
Thanks for the feedback. I’ve just rebased and will try to address the comments shortly.

**Comment by vbgl** [comment]
This needs more thought.

**Pull request closed without merging**
