### PR TITLE
checksafety: reset A/M-var conversion table

### LINKED ISSUE #314: Checksafety crash: Failure("Environment.make: duplicated variable names")
Here is a minimal example leading to a crash (when calling `jasminc -checksafety`):

~~~
inline fn f(reg u32 i) {
  reg bool zf;
  while {
    _,_,_,zf,i = #DEC_32(i);
  } (!zf)
}

inline fn g() {
  reg u32 i;
  i = 1;
  f(2);
}

export fn test1() { g(); }
export fn test2() { g(); }
~~~

Apparently, the same variable name (here `v_i.156`) appears twice in the environments

### PR DESCRIPTION
**Pull request by vbgl**
Fixes #314

### CODE REVIEW

**Comment by vbgl** [comment]
Just rebased to fix merge conflicts; CI is happy: https://gitlab.com/jasmin-lang/jasmin/-/pipelines/738010398

**Comment by eponier** [comment]
Is this an easy hack or the proper way to fix this problem?

**Comment by vbgl** [comment]
Ideally it would be better to get rid of mutable global variables.

**Review by eponier — APPROVED** [review]
Good enough.

**Comment by eponier** [comment]
Green (https://gitlab.com/jasmin-lang/jasmin/-/pipelines/742827214)!

**Comment by vbgl** [comment]
Merci! One little step closer to be able to check libjade!

**Pull request merged**
