### PR TITLE
[CI] EasyCrypt: use why3 1.6.0

### PR DESCRIPTION
**Pull request by vbgl**
Fix after https://github.com/EasyCrypt/easycrypt/pull/352

### CODE REVIEW

**Review by eponier — APPROVED** [review]
I trust you on these nix-related things. But why do we need these patches? We use old versions of EasyCrypt with the last version of Why3?

**Comment by vbgl** [comment]
It’s not old. It’s the latest up-to-date released version of EasyCrypt.

**Comment by eponier** [comment]
If I understand correctly, this means that these patches will be removed at the time of the next release of EasyCrypt?

**Comment by vbgl** [comment]
Yes.

**Pull request merged**
