### PR TITLE
Check bounds in array-expansion

### PR DESCRIPTION
**Pull request by vbgl**
cc @kcning

### CODE REVIEW

**Comment by vbgl** [comment]
Marking as draft waiting for the corresponding issue to be opened.
CI: https://gitlab.com/jasmin-lang/jasmin/-/pipelines/749241798

**Comment by vbgl** [comment]
Fixes #333

**Review by eponier — APPROVED** [review]
Clearer message, indeed!

**Comment by vbgl** [comment]
Rebased to fix merge conflicts in CHANGELOG
CI: https://gitlab.com/jasmin-lang/jasmin/-/pipelines/750427249

**Pull request merged**
