### PR TITLE
Move expected SCT errors to individual files, add an annotation to exclude functions from test cases

### PR DESCRIPTION
**Pull request by sarranz**
I propose to move the test cases for SCT error messages to individual files.
With the current single file, every time I edited a test case all line numbers changed
Besides, we need to keep the list in sct_errors.ml updated

I added an annotation to exclude auxiliary functions from the tests. Before we were using the inline annotation for this, but for some cases the checker acts differently on inline functions and subroutines, so it would be good to be able to test both.

### CODE REVIEW

**Review by vbgl — COMMENTED** [review]
Please amend the README to reflect the `inline` → `#[test = nosct]` change.

If the motivation for scattering the test case into many files is line numbers, there might be a better fix (e.g., that just deals with line numbers / formatting of error messages).

**Comment by sarranz** [comment]
I'm open to suggestions on how to deal with just line numbers instead

**Comment by vbgl** [comment]
See #648.

**Comment by sarranz** [comment]
I think that's better, thanks! I'll do a separate PR for the annotation part

**Pull request closed without merging**
