### PR TITLE
CI: disable the “cache dependencies” job

### PR DESCRIPTION
**Pull request by vbgl**
Something is wrong with CI. Who knows what…

This PR might help.

### CODE REVIEW

**Review by eponier — APPROVED** [review]

**Comment by vbgl** [comment]
This did not work. Does anyone knows how to reliably disable a gitlab-ci job?

**Comment by eponier** [comment]
`when: never` ?

**Comment by eponier** [comment]
https://docs.gitlab.com/ee/ci/jobs/index.html#hide-jobs

**Comment by vbgl** [comment]
Like this: https://github.com/jasmin-lang/jasmin/pull/998?

**Comment by eponier** [comment]
This is what I understand, let's try.

**Pull request merged**
